### ISSUE TITLE
Register syntax

### ISSUE THREAD

**Issue by dagronlund** [wavelet-eda/quark#36]
I am thinking we could use this syntax for defining registers?
```
Reg[Bit[32], 'h34] my_reg(clk, rst);
```
Where you could then on a later line write
```
my_reg = 'h43;
```
Do we want to formalize this?

**Comment by Spaceman1701** [comment]
`reg[RST_VALUE](clk_sig, rst_sig) TypeName value_name;`

Should reset imply `mut`?

**Comment by dagronlund** [comment]
Neither a reset nor a reg keyword define that a register is mutable, you have to put that keyword in front. Of note registers are a special kind of immutable by default, where if they are not assigned to at declaration and are not mutable, they can be assigned to either once or zero times in any evaluated branch.
